const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //languages change
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_CREATE_INFO_SUCCESS: 'USER_CREATE_INFO_SUCCESS',
    USER_CREATE_INFO_FAILED: 'USER_CREATE_INFO_FAILED',
    IMPORT_DATA_SUCCESS: 'IMPORT_DATA_SUCCESS',

    //user CRUD manage
    CREATE_USER_CRUD_SUCCESS: 'CREATE_USER_CRUD_SUCCESS',
    CREATE_USER_CRUD_FAILED: 'CREATE_USER_CRUD_FAILED',
    GET_LIST_USER_CRUD_SUCCESS: 'GET_LIST_USER_CRUD_SUCCESS',
    GET_LIST_USER_CRUD_FAILED: 'GET_LIST_USER_CRUD_FAILED',
    EDIT_USER_CRUD_SUCCESS: 'EDIT_USER_CRUD_SUCCESS',
    EDIT_USER_CRUD_FAILED: 'EDIT_USER_CRUD_FAILED',
    DELETE_USER_CRUD_SUCCESS: 'DELETE_USER_CRUD_SUCCESS',
    DELETE_USER_CRUD_FAILED: 'DELETE_USER_CRUD_FAILED',
    //get all codes
    GET_POSITION_CODE_SUCCESS: 'GET_POSITION_CODE_SUCCESS',
    GET_POSITION_CODE_FAILED: 'GET_POSITION_CODE_FAILED',
    GET_ROLE_CODE_SUCCESS: 'GET_ROLE_CODE_SUCCESS',
    GET_ROLE_CODE_FAILED: 'GET_ROLE_CODE_FAILED',
    GET_STATUS_CODE_SUCCESS: 'GET_STATUS_CODE_SUCCESS',
    GET_STATUS_CODE_FAILED: 'GET_STATUS_CODE_FAILED',

    //get all demoFeatures
    CREATE_DEMO_FEATURES_SUCCESS: 'CREATE_DEMO_FEATURES_SUCCESS',
    CREATE_DEMO_FEATURES_FAILED: 'CREATE_DEMO_FEATURES_FAILED',
    GET_ALL_DEMO_FEATURES_SUCCESS: 'GET_ALL_DEMO_FEATURES_SUCCESS',
    GET_ALL_DEMO_FEATURES_FAILED: 'GET_ALL_DEMO_FEATURES_FAILED',

    //manage category
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILED: 'CREATE_CATEGORY_FAILED',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILED: 'GET_ALL_CATEGORY_FAILED',
    EDIT_CATEGORY_SUCCESS: 'EDIT_CATEGORY_SUCCESS',
    EDIT_CATEGORY_FAILED: 'EDIT_CATEGORY_FAILED',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILED: 'DELETE_CATEGORY_FAILED',
    //manage article
    CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
    CREATE_ARTICLE_FAILED: 'CREATE_ARTICLE_FAILED',
    GET_LIST_ARTICLE_SUCCESS: 'GET_LIST_ARTICLE_SUCCESS',
    GET_LIST_ARTICLE_FAILED: 'GET_LIST_ARTICLE_FAILED',
    EDIT_ARTICLE_SUCCESS: 'EDIT_ARTICLE_SUCCESS',
    EDIT_ARTICLE_FAILED: 'EDIT_ARTICLE_FAILED',
    DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
    DELETE_ARTICLE_FAILED: 'DELETE_ARTICLE_FAILED',
    CHANGE_STATUS_ARTICLE_SUCCESS: 'CHANGE_STATUS_ARTICLE_SUCCESS',
    CHANGE_STATUS_ARTICLE_FAILED: 'CHANGE_STATUS_ARTICLE_FAILED',
})

export default actionTypes;